#!/usr/bin/env bash
set -euo pipefail

# ─── ClawHQ Installer ─────────────────────────────────────────────────────

BOLD="\033[1m"
CYAN="\033[36m"
GREEN="\033[32m"
YELLOW="\033[33m"
RED="\033[31m"
RESET="\033[0m"

header() { echo -e "\n${CYAN}${BOLD}$1${RESET}"; }
info()   { echo -e "  ${GREEN}✓${RESET} $1"; }
warn()   { echo -e "  ${YELLOW}!${RESET} $1"; }
err()    { echo -e "  ${RED}✗${RESET} $1"; exit 1; }
ask()    { echo -en "  ${BOLD}$1${RESET} "; }

clear
echo -e "${CYAN}${BOLD}"
cat << 'EOF'
   _____ _               _    _  _____
  / ____| |             | |  | |/ __  \
 | |    | | __ ___      _| |__| | |  | |
 | |    | |/ _` \ \ /\ / /  __  | |  | |
 | |____| | (_| |\ V  V /| |  | | |__| |
  \_____|_|\__,_| \_/\_/ |_|  |_|\____/

EOF
echo -e "${RESET}"
echo -e "  The unified AI agent platform."
echo -e "  OpenClaw + OpenFang + Paperclip, in one place.\n"
echo -e "  ${YELLOW}This will take about 2 minutes.${RESET}\n"

# ─── Prerequisites ─────────────────────────────────────────────────────────

header "Checking prerequisites"

command -v docker &>/dev/null || err "Docker is required. Install at https://docker.com/get-started"
docker info &>/dev/null || err "Docker daemon is not running. Start Docker and try again."
command -v docker &>/dev/null && docker compose version &>/dev/null || err "Docker Compose v2 is required."

info "Docker $(docker --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')"
info "Docker Compose $(docker compose version --short)"

# ─── Check for existing install ────────────────────────────────────────────

if [ -f .env ]; then
  warn ".env already exists."
  ask "Overwrite it? (y/N)"
  read -r overwrite
  [[ "$overwrite" =~ ^[Yy]$ ]] || { echo "  Keeping existing .env. Run 'docker compose up -d' to start."; exit 0; }
fi

# ─── Gather config ─────────────────────────────────────────────────────────

header "Configuration"
echo -e "  Answer a few questions to get set up.\n"

# Public URL
ask "Your public URL (or press enter for http://localhost:3500):"
read -r PUBLIC_URL
PUBLIC_URL="${PUBLIC_URL:-http://localhost:3500}"

# Anthropic API key
ask "Anthropic API key (sk-ant-... — required for Claude agents):"
read -r -s ANTHROPIC_KEY
echo
[ -z "$ANTHROPIC_KEY" ] && warn "No Anthropic key set. Agents requiring Claude will not work."

# Optional keys
ask "OpenAI API key (optional, press enter to skip):"
read -r -s OPENAI_KEY
echo

ask "Groq API key (optional, press enter to skip):"
read -r -s GROQ_KEY
echo

# Discord bot token
ask "Discord bot token (optional — needed for Discord channel):"
read -r -s DISCORD_TOKEN
echo

# ─── Generate secrets ──────────────────────────────────────────────────────

header "Generating secrets"

gen_secret() { openssl rand -base64 32 | tr -d '\n/+='; }

POSTGRES_PASSWORD=$(gen_secret)
BETTER_AUTH_SECRET=$(gen_secret)
OPENCLAW_GATEWAY_TOKEN=$(gen_secret)
NEXTAUTH_SECRET=$(gen_secret)

info "Postgres password generated"
info "Auth secrets generated"
info "Gateway token generated"

# ─── Write .env ────────────────────────────────────────────────────────────

header "Writing .env"

cat > .env << EOF
# ClawHQ — generated by install.sh on $(date)
# Edit this file to change configuration, then run: docker compose up -d

# ── Platform ──────────────────────────────────────────────────────────────
CLAWHQ_PUBLIC_URL=${PUBLIC_URL}
CLAWHQ_PORT=3500
TZ=$(date +%Z || echo UTC)

# ── Secrets (auto-generated — do not share) ───────────────────────────────
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
OPENCLAW_GATEWAY_TOKEN=${OPENCLAW_GATEWAY_TOKEN}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

# ── LLM Keys ──────────────────────────────────────────────────────────────
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}
OPENAI_API_KEY=${OPENAI_KEY}
GROQ_API_KEY=${GROQ_KEY}

# ── Channels ──────────────────────────────────────────────────────────────
DISCORD_BOT_TOKEN=${DISCORD_TOKEN}
TELEGRAM_BOT_TOKEN=
SLACK_BOT_TOKEN=
SLACK_APP_TOKEN=

# ── OpenClaw ──────────────────────────────────────────────────────────────
OPENCLAW_PORT=18789
CLAUDE_AI_SESSION_KEY=

# ── Service Ports ─────────────────────────────────────────────────────────
OPENFANG_PORT=4200
PAPERCLIP_PORT=3100
EOF

info ".env written"

# ─── Build & start ─────────────────────────────────────────────────────────

header "Building ClawHQ"
echo -e "  ${YELLOW}First build takes 5-10 minutes (compiling Rust for OpenFang).${RESET}"
echo -e "  Grab a coffee — this only happens once.\n"

docker compose build --parallel 2>&1 | grep -E "(Successfully|error|ERROR|=>)" | head -40 || true

header "Starting services"

docker compose up -d

echo ""
echo -e "${GREEN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${GREEN}${BOLD}  ClawHQ is running!${RESET}"
echo -e "${GREEN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
echo -e "  Dashboard   →  ${CYAN}${BOLD}${PUBLIC_URL}${RESET}"
echo -e "  OpenClaw    →  ${PUBLIC_URL/3500/18789}"
echo -e "  Paperclip   →  ${PUBLIC_URL/3500/3100}"
echo -e "  OpenFang    →  ${PUBLIC_URL/3500/4200}"
echo ""
echo -e "  Run ${BOLD}docker compose logs -f${RESET} to watch logs."
echo -e "  Run ${BOLD}docker compose down${RESET} to stop everything."
echo ""
